### crear equipo
POST http://localhost:3000/teams
Content-Type: application/json
Authorization: Bearer token

{
    "name": "PSG",
    "players": [{"name" : "messi"}, {"name" : "mbappe"}, {"name" : "neymar"}, {"name" : "ramos"}],
    "manager": "pochetino"
}

### obtener todos los equipos
GET http://localhost:3000/teams

### obtener todos los equipos por posiciones, sin datos de la plantilla (ideal para tablas de puntaje de la liga) 
GET http://localhost:3000/teams/positions

### obtener un equipo en específico
GET http://localhost:3000/teams/6194e685a0222a2e76ca9e01

### borrar un equipo
DELETE http://localhost:3000/teams/619770091d13029793503c12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzYXJpbzFAdGVzdC5jb20iLCJhZG1pbklkIjoiNjE5NGUwMWI4Nzg0MDU3YzMwYTkxODFlIiwiaWF0IjoxNjM3MzE0NDk3LCJleHAiOjE2MzczMjE2OTd9.YM8aN21p2GA5hrdIAxR6gaQnurYaq1HbXhXqLS2rHp0

### editar nombre de equipo
PATCH http://localhost:3000/teams/name
Content-Type: application/json
Authorization: Bearer token

{
    "teamId": "6194e70aa0222a2e76ca9e25",
    "newName": "Borussia Dortmund"
}

### editar url del escudo
PATCH http://localhost:3000/teams/badge
Content-Type: application/json
Authorization: Bearer token

{
    "teamId": "6194e70aa0222a2e76ca9e25"
}

### añadir jugador (se creará un ID para el jugador en el momento de ser añadido)
PATCH http://localhost:3000/teams/add-player
Content-Type: application/json
Authorization: Bearer token

{
    "teamId": "6194e70aa0222a2e76ca9e25",
    "name": "malen"
}

### borrar jugador
POST http://localhost:3000/teams/delete-player
Content-Type: application/json
Authorization: Bearer token

{
    "teamId": "6194e70aa0222a2e76ca9e25",
    "playerId": "6194e7e35696ba8ff06b5558"
}

### editar jugador
PATCH http://localhost:3000/teams/edit-player
Content-Type: application/json
Authorization: Bearer token

{
    "teamId": "6194e70aa0222a2e76ca9e25",
    "playerId": "6194e70aa0222a2e76ca9e29",
    "newName": "Courtuois"
}

### recuperar jugadores de un equipo específico
GET http://localhost:3000/teams/players/6194e70aa0222a2e76ca9e25


### recuperar plantilla de un equipo específico
GET http://localhost:3000/teams/squad/6194e70aa0222a2e76ca9e25


### añadir o cambiar técnico de un equipo
POST http://localhost:3000/teams/manager
Content-Type: application/json
Authorization: Bearer token

{
    "teamId": "6194e70aa0222a2e76ca9e25",
    "manager": "Ancelotti"
}


### recuperar técnico de un equipo
GET http://localhost:3000/teams/manager/6194e70aa0222a2e76ca9e25

